version: '3.9'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: .
    command: daphne backend.asgi:application -b 0.0.0.0 -p 8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  wsgi:
    build: .
    command: gunicorn backend.wsgi:application -b 0.0.0.0:8001
    volumes:
      - .:/code
    expose:
      - "8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - wsgi
    restart: always
